server:
  port: 8003
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: 123456
    publisher-confirm-type: correlated
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual  #开启ACK
        retry:
          max-attempts: 5  #重试次数
          initial-interval: 5000  #重试间隔时间
          enabled: true  #开启消费重试
        default-requeue-rejected: false  #重试次数超过上面的设置之后是否丢弃（false不丢弃时需要写相应代码将该消息加入死信队列
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springtest?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    # 使用druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    # druid连接池相关配置
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
      serialization:
        write-dates-as-timestamps: false
  mybatis-plus:
    configuration:
      map-underscore-to-camel-case: true
      auto-mapping-behavior: full
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations: classpath*:mapperxml/**/*Mapper.xml
    type-aliases-package: com.cjw.boot.model
    global-config:
      # 逻辑删除配置
      db-config:
        # 删除前
        logic-not-delete-value: 0
        # 删除后
        logic-delete-value: 1
  application:
    name: orderSys
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
